version: '3'

services:
  budget-server:
    image: ghcr.io/cyrill10/budget.server:latest
    restart: always    
    environment:
      SPRING_DATA_MONGODB_DATABASE: budget
      SPRING_DATA_MONGODB_URI: "${MONGO_URI}"
      auth_username: "${AUTH_USERNAME}"
      auth_password: "${AUTH_PASSWORD}"
    ports:
      - "8085:8080"
