version: '3'

services:

  budget-server:
    image: ghcr.io/cyrill10/budget.server:latest
    restart: always    
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.datasource.url": "jdbc:mysql://budget-db:3306/budget?useLegacyDatetimeCode=false",
        "spring.datasource.username": "${SERVER.DATABASE.USERNAME}",
        "spring.datasource.password": "${SERVER.DATABASE.PASSWORD}"
     }'
    ports:
      - "8085:8085"

  budget-db:
    image: mysql:8.0.13
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB.ROOT.PASSWORD}
      MYSQL_DATABASE: budget
    ports:
      - "3306:3306"
